#---------------------------------#
#  Build Script                   #
#---------------------------------#
build_script:
  - ps: .\buildscripts\build.ps1 quick-deploy

# Tests
test: off

#---------------------------------#
#        Branches to build        #
#---------------------------------#
branches:
  # Whitelist
  only:
    - develop
    - master
    - /release/.*/
    - /hotfix/.*/

artifacts:
  - path: 'C:\projects\boxstarter\BuildArtifacts\Boxstarter.*.zip'
  - path: 'C:\projects\boxstarter\BuildArtifacts\Boxstarter.*.nupkg'
